import 'package:super_xo/controllers/language_controller.dart';

/// Minimal translations map for quick/simple localization.
/// Keys are string identifiers used across the app.
const Map<String, Map<String, String>> _translations = {
  'en': {
    'restart_title': 'Restart game?',
    'restart_message': 'This will clear the board and reset the game.',
    'cancel': 'Cancel',
    'restart': 'Restart',
    'game_over_title': 'Game Over',
    'game_over_draw': 'The game is a draw!',
    'game_over_winner': '{winner} wins the ultimate game🏆',
    'play_again': 'Play again',
    'close': 'Close',
    'language_english': 'English',
    'language_arabic': 'العربية',
    'toggle_language_tool': 'Toggle Language',
    'change_color_tool': 'Change Color',
    'change_theme_tool': 'Change Theme dark-light',
    'restart_game_tool': 'Restart Game',
    'undo_tool': 'Undo',
    'settings_title': 'Settings',
    'theme_section': 'Theme',
    'dark_mode': 'Dark Mode',
    'dark_mode_description': 'Switch between light and dark theme',
    'language_section': 'Language',
    'color_theme_section': 'Color Theme',
    'color_theme_description': 'Choose your preferred color scheme',
    'pink': 'Pink',
    'blue': 'Blue',
    'green': 'Green',
    'orange': 'Orange',
    'purple': 'Purple',
    'cyan': 'Cyan',
    'brown': 'Brown',
    'grey': 'Grey',
    'start_menu_title': 'Super XO',
    'play_local': 'Play Locally',
    'play_online': 'Play Online',
    'settings': 'Settings',
    'create_room': 'Create Room',
    'join_room': 'Join Room',
    'room_code': 'Room Code',
    'waiting_for_opponent': 'Waiting for opponent...',
    'room_created': 'Room Created',
    'share_code': 'Share this code with your friend:',
    'enter_room_code': 'Enter room code',
    'join': 'Join',
    'back': 'Back',
    'you_are': 'You are',
    'opponent_left': 'Opponent Left',
    'opponent_disconnected': 'Your opponent has disconnected',
    'return_to_menu': 'Return to Menu',
    'exit_game': 'Exit Game',
    'exit_title': 'Exit Game?',
    'exit_message': 'Are you sure you want to exit?',
    'exit': 'Exit',
    'server_unreachable':
        'Cannot reach server. Please check your internet connection.',
    'connection_failed': 'Failed to connect to server. Please try again.',
    'not_connected':
        'Not connected to server. Please wait or retry connection.',
    'retry_connection': 'Retry Connection',
    'player_disconnected': 'Player Disconnected',
    'waiting_reconnect': 'Waiting for player to reconnect...',
    'reconnecting': 'Reconnecting...',
    'room_timeout': 'Room Timeout',
  },
  'ar': {
    'restart_title': 'إعادة بدء اللعبة؟',
    'restart_message': 'سيؤدي ذلك إلى مسح اللوحة وإعادة ضبط اللعبة',
    'cancel': 'إلغاء',
    'restart': 'إعادة بدء اللعبة',
    'game_over_title': '!!انتهت اللعبة',
    'game_over_draw': 'اللعبة انتهت بالتعادل!',
    'game_over_winner': '🏆 فاز في اللعبة {winner} ',
    'play_again': 'العب مرة أخرى',
    'close': 'إغلاق',
    'language_english': 'English',
    'language_arabic': 'العربية',
    'toggle_language_tool': 'تغيير اللغة',
    'change_color_tool': 'تغيير اللون',
    'change_theme_tool': 'تغيير المظهر داكن-فاتح',
    'restart_game_tool': 'إعادة اللعبة',
    'undo_tool': 'تراجع',
    'settings_title': 'الإعدادات',
    'theme_section': 'المظهر',
    'dark_mode': 'الوضع الداكن',
    'dark_mode_description': 'التبديل بين المظهر الفاتح والداكن',
    'language_section': 'اللغة',
    'color_theme_section': 'نظام الألوان',
    'color_theme_description': 'اختر نظام الألوان المفضل لديك',
    'pink': 'وردي',
    'blue': 'أزرق',
    'green': 'أخضر',
    'orange': 'برتقالي',
    'purple': 'بنفسجي',
    'cyan': 'سماوي',
    'brown': 'بني',
    'grey': 'رمادي',
    'start_menu_title': 'سوبر XO',
    'play_local': 'العب محلياً',
    'play_online': 'العب عبر الإنترنت',
    'settings': 'الإعدادات',
    'create_room': 'إنشاء غرفة',
    'join_room': 'انضم إلى غرفة',
    'room_code': 'رمز الغرفة',
    'waiting_for_opponent': 'في انتظار الخصم...',
    'room_created': 'تم إنشاء الغرفة',
    'share_code': 'شارك هذا الرمز مع صديقك:',
    'enter_room_code': 'أدخل رمز الغرفة',
    'join': 'انضم',
    'back': 'رجوع',
    'you_are': 'أنت',
    'opponent_left': 'غادر الخصم',
    'opponent_disconnected': 'لقد انقطع اتصال خصمك',
    'return_to_menu': 'العودة إلى القائمة',
    'exit_game': 'الخروج من اللعبة',
    'exit_title': 'الخروج من اللعبة؟',
    'exit_message': 'هل أنت متأكد من الخروج؟',
    'exit': 'خروج',
    'server_unreachable':
        'لا يمكن الوصول إلى الخادم. يرجى التحقق من اتصالك بالإنترنت.',
    'connection_failed': 'فشل الاتصال بالخادم. يرجى المحاولة مرة أخرى.',
    'not_connected': 'غير متصل بالخادم. يرجى الانتظار أو إعادة المحاولة.',
    'retry_connection': 'إعادة المحاولة',
    'player_disconnected': 'انقطع اتصال اللاعب',
    'waiting_reconnect': 'في انتظار إعادة اتصال اللاعب...',
    'reconnecting': 'جاري إعادة الاتصال...',
    'room_timeout': 'مهلة الغرفة انتهت',
  },
};

/// Quick lookup. Uses the current value of [LanguageController.lang].
String tr(String key) {
  final code = LanguageController.lang.value;
  return _translations[code]?[key] ?? _translations['en']?[key] ?? key;
}

/// Helper that does a simple placeholder substitution for {winner}.
String trWithWinner(String key, String winner) {
  final template = tr(key);
  return template.replaceAll('{winner}', winner);
}
